movies:
  - name: "Odyssey IMAX Palazzo"
    url: "https://in.bookmyshow.com/movies/chennai/the-odyssey/buytickets/ET00480917/20260830?etCodes=ET00480917&language=english&refEventCode=ET00480917"
    theatre_filter: "Palazzo"
